In [1]:
import json
with open("./Labelled_230_car_images/Datalabeling_ObjectLabels_230.json") as access_json:
    read_content = json.load(access_json)

In [2]:
file_access = read_content["Sequence"]

In [3]:
for file_data in file_access:
    pass
label_name = file_data['Labels']

In [4]:
for device_data in label_name:
    pass
device_name = device_data['Devices']

In [5]:
for Channels_data in device_name:
    pass
channels_name = Channels_data['Channels']

In [6]:
for Object_data in channels_name:
    pass
object_names = Object_data['ObjectLabels']

In [7]:
for user in object_names:
    pass

userdata0 = user["TimeStamp"]
print("TimeStamp:",str(userdata0)+'.jpeg')

userdata1 = user['FrameNumber']
print("FrameNumber:",userdata1)

userdata2_1 = user['FrameObjectLabels'][0]['category']
print("category:",userdata2_1)

userdata2_2 = user['FrameObjectLabels'][0]['Trackid']
print("Trackid:",userdata2_2)

userdata2_3 = user['FrameObjectLabels'][0]['width']
print("width:",userdata2_3)

userdata2_4 = user['FrameObjectLabels'][0]['height']
print("height:",userdata2_4)

userdata2_5 = user['FrameObjectLabels'][0]['shape']['x']
print("x:",userdata2_5)

userdata2_6 = user['FrameObjectLabels'][0]['shape']['y']
print("y:",userdata2_6)

TimeStamp: 1469119107937991.jpeg
FrameNumber: 82
category: Car
Trackid: 23
width: 108.04045867919922
height: 49.02216339111328
x: [1.1072396039962769, 109.14769744873047, 109.14769744873047, 1.1072396039962769]
y: [268.3349609375, 268.3349609375, 317.35711669921875, 317.35711669921875]

In [8]:
def get_data():
    
    question_access = read_content["Sequence"]
    
    for question_data in question_access:
        replies_access = question_data['Labels']
        
        for replies_data in replies_access:
            user_name = replies_data['Devices']
            
            for Channels_data in user_name:
                channels_name = Channels_data['Channels']
                
                for Object_data in channels_name:
                    object_names = Object_data['ObjectLabels']
                    
                    for user in object_names: 
                        userdata0 = user["TimeStamp"]
                        a=('MFC4xxLongImageRight'+ str(userdata0)+ '.jpeg')
                        userdata1 = user['FrameNumber']
                        userdata2 = user['FrameObjectLabels']                        
                        
                        n=len(userdata2)                        
                        for i in range(n):
                            
                            print("TimeStamp:",a)
                            print("FrameNumber:",userdata1)
                            
                            userdata2_1 = user['FrameObjectLabels'][i]['category']
                            print("category:",userdata2_1)

                            userdata2_2 = user['FrameObjectLabels'][i]['Trackid']
                            print("Trackid:",userdata2_2)

                            userdata2_3 = user['FrameObjectLabels'][i]['width']
                            print("width:",userdata2_3)

                            userdata2_4 = user['FrameObjectLabels'][i]['height']
                            print("height:",userdata2_4)

                            userdata2_5 = user['FrameObjectLabels'][i]['shape']['x'][0]
                            print("x:",userdata2_5)

                            userdata2_6 = user['FrameObjectLabels'][i]['shape']['y'][0]
                            print("y:",userdata2_6)
                            
                            TimeStamp.append(a)
                            FrameNumber.append(userdata1)
                            category.append(userdata2_1)
                            Trackid.append(userdata2_2)
                            width.append(userdata2_3)
                            height.append(userdata2_4)
                            x.append(userdata2_5)
                            y.append(userdata2_6)

In [9]:
TimeStamp, FrameNumber, category, Trackid, width, height, x, y = [],[],[],[],[],[],[],[]

In [10]:
b=get_data()
print(b)

TimeStamp: MFC4xxLongImageRight1469119107817429.jpeg
FrameNumber: 80
category: Car
Trackid: 23
width: 112.24987030029297
height: 48.340721130371094
x: 20.414987564086914
y: 267.9471740722656
TimeStamp: MFC4xxLongImageRight1469119107817429.jpeg
FrameNumber: 80
category: Car
Trackid: 25
width: 37.10524368286133
height: 31.477767944335938
x: 488.7315673828125
y: 246.1448516845703
TimeStamp: MFC4xxLongImageRight1469119107817429.jpeg
FrameNumber: 80
category: Car
Trackid: 17
width: 130.82135009765625
height: 100.53882598876953
x: 271.0704345703125
y: 239.28012084960938
TimeStamp: MFC4xxLongImageRight1469119105707648.jpeg
FrameNumber: 182
category: Car
Trackid: 26
width: 92.2358169555664
height: 34.95623779296875
x: 1016.9940795898438
y: 238.688232421875
TimeStamp: MFC4xxLongImageRight1469119105707648.jpeg
FrameNumber: 182
category: Car
Trackid: 25
width: 32.81050491333008
height: 29.315673828125
x: 505.68878173828125
y: 251.37728881835938
TimeStamp: MFC4xxLongImageRight1469119105707648.jpeg
FrameNumber: 182
category: Car
Trackid: 24
width: 94.28028869628906
height: 38.198333740234375
x: 60.73774337768555
y: 264.0743408203125
TimeStamp: MFC4xxLongImageRight1469119105707648.jpeg
FrameNumber: 182
category: Car
Trackid: 17
width: 176.73684692382812
height: 111.7741928100586
x: 307.47369384765625
y: 236.85484313964844
TimeStamp: MFC4xxLongImageRight1469119100282487.jpeg
FrameNumber: 49
category: Car
Trackid: 21
width: 53.68619918823242
height: 37.0
x: 330.4347839355469
y: 249.86656188964844
TimeStamp: MFC4xxLongImageRight1469119100282487.jpeg
FrameNumber: 49
category: Car
Trackid: 17
width: 43.189510345458984
height: 32.11011505126953
x: 435.44268798828125
y: 245.92218017578125
TimeStamp: MFC4xxLongImageRight1469119098172705.jpeg
FrameNumber: 57
category: Car
Trackid: 21
width: 24.394367218017578
height: 22.117374420166016
x: 421.3214111328125
y: 248.2874298095703
TimeStamp: MFC4xxLongImageRight1469119098172705.jpeg
FrameNumber: 57
category: Car
Trackid: 20
width: 31.47367286682129
height: 29.274192810058594
x: 384.9473876953125
y: 249.27420043945312
TimeStamp: MFC4xxLongImageRight1469119098172705.jpeg
FrameNumber: 57
category: Car
Trackid: 15
width: 119.93055725097656
height: 74.45304870605469
x: 80.32508087158203
y: 245.20794677734375
TimeStamp: MFC4xxLongImageRight1469119098172705.jpeg
FrameNumber: 57
category: Car
Trackid: 19
width: 53.86842346191406
height: 45.73896026611328
x: 328.65789794921875
y: 238.12582397460938
TimeStamp: MFC4xxLongImageRight1469119098172705.jpeg
FrameNumber: 57
category: Car
Trackid: 18
width: 76.7634048461914
height: 49.829490661621094
x: 251.89447021484375
y: 244.89712524414062
TimeStamp: MFC4xxLongImageRight1469119098172705.jpeg
FrameNumber: 57
category: Car
Trackid: 17
width: 30.146503448486328
height: 22.120025634765625
x: 467.5987548828125
y: 250.54444885253906
TimeStamp: MFC4xxLongImageRight1469119103055347.jpeg
FrameNumber: 138
category: Car
Trackid: 23
width: 41.15789031982422
height: 33.822723388671875
x: 517.6148681640625
y: 247.01097106933594
TimeStamp: MFC4xxLongImageRight1469119103055347.jpeg
FrameNumber: 138
category: Car
Trackid: 22
width: 136.28102111816406
height: 67.28623962402344
x: 52.007720947265625
y: 255.1062469482422
TimeStamp: MFC4xxLongImageRight1469119103055347.jpeg
FrameNumber: 138
category: Car
Trackid: 17
width: 99.2631607055664
height: 65.6451644897461
x: 411.5789489746094
y: 242.1774139404297
TimeStamp: MFC4xxLongImageRight1469119103718422.jpeg
FrameNumber: 149
category: Car
Trackid: 23
width: 41.15791320800781
height: 33.822723388671875
x: 507.529541015625
y: 250.55906677246094
TimeStamp: MFC4xxLongImageRight1469119103718422.jpeg
FrameNumber: 149
category: Car
Trackid: 17
width: 130.73684692382812
height: 77.17742156982422
x: 381.3157958984375
y: 238.6290283203125
TimeStamp: MFC4xxLongImageRight1469119101608641.jpeg
FrameNumber: 62
category: Car
Trackid: 23
width: 41.157894134521484
height: 33.822715759277344
x: 478.15789794921875
y: 242.34031677246094
TimeStamp: MFC4xxLongImageRight1469119101608641.jpeg
FrameNumber: 62
category: Car
Trackid: 22
width: 110.62679290771484
height: 41.792972564697266
x: 293.6889953613281
y: 244.2975616455078
TimeStamp: MFC4xxLongImageRight1469119101608641.jpeg
FrameNumber: 62
category: Car
Trackid: 21
width: 148.81170654296875
height: 79.0291976928711
x: 40.04718780517578
y: 246.40017700195312
TimeStamp: MFC4xxLongImageRight1469119101608641.jpeg
FrameNumber: 62
category: Car
Trackid: 17
width: 67.0
height: 47.0
x: 422.7241516113281
y: 243.85911560058594
TimeStamp: MFC4xxLongImageRight1469119106491282.jpeg
FrameNumber: 195
category: Car
Trackid: 23
width: 50.042667388916016
height: 39.226951599121094
x: 252.5087890625
y: 265.00885009765625
TimeStamp: MFC4xxLongImageRight1469119106491282.jpeg
FrameNumber: 195
category: Car
Trackid: 26
width: 99.96559143066406
height: 38.04763412475586
x: 1053.89794921875
y: 237.47076416015625
TimeStamp: MFC4xxLongImageRight1469119106491282.jpeg
FrameNumber: 195
category: Car
Trackid: 25
width: 34.62400436401367
height: 30.228656768798828
x: 495.8489685058594
y: 249.55055236816406
TimeStamp: MFC4xxLongImageRight1469119106491282.jpeg
FrameNumber: 195
category: Car
Trackid: 17
width: 176.73684692382812
height: 111.7741928100586
x: 301.4210510253906
y: 246.61289978027344
TimeStamp: MFC4xxLongImageRight1469119106370721.jpeg
FrameNumber: 71
category: Car
Trackid: 23
width: 38.0
height: 38.0
x: 267.9071044921875
y: 267.021484375
TimeStamp: MFC4xxLongImageRight1469119106370721.jpeg
FrameNumber: 71
category: Car
Trackid: 26
width: 101.06809997558594
height: 37.458457946777344
x: 1050.33203125
y: 238.22335815429688
TimeStamp: MFC4xxLongImageRight1469119106370721.jpeg
FrameNumber: 71
category: Car
Trackid: 25
width: 34.263126373291016
height: 30.046964645385742
x: 496.88421630859375
y: 250.04592895507812
TimeStamp: MFC4xxLongImageRight1469119106370721.jpeg
FrameNumber: 71
category: Car
Trackid: 17
width: 166.51617431640625
height: 108.75076293945312
x: 296.0767517089844
y: 243.62950134277344
TimeStamp: MFC4xxLongImageRight1469119094736776.jpeg
FrameNumber: 0
category: Car
Trackid: 3
width: 21.789474487304688
height: 26.052631378173828
x: 409.15789794921875
y: 257.0526428222656
TimeStamp: MFC4xxLongImageRight1469119094736776.jpeg
FrameNumber: 0
category: Car
Trackid: 2
width: 60.52631759643555
height: 57.31578826904297
x: 279.631591796875
y: 248.36842346191406
TimeStamp: MFC4xxLongImageRight1469119094736776.jpeg
FrameNumber: 0
category: Car
Trackid: 1
width: 41.157894134521484
height: 50.3684196472168
x: 347.4210510253906
y: 248.36842346191406
TimeStamp: MFC4xxLongImageRight1469119094736776.jpeg
FrameNumber: 0
category: Car
Trackid: 0
width: 104.10526275634766
height: 52.105262756347656
x: 169.4736785888672
y: 264.0
TimeStamp: MFC4xxLongImageRight1469119107154354.jpeg
FrameNumber: 206
category: Car
Trackid: 23
width: 101.420654296875
height: 46.863075256347656
x: 154.8826446533203
y: 264.7962646484375
TimeStamp: MFC4xxLongImageRight1469119107154354.jpeg
FrameNumber: 206
category: Car
Trackid: 26
width: 81.74700927734375
height: 38.91665267944336
x: 1092.2598876953125
y: 235.75390625
TimeStamp: MFC4xxLongImageRight1469119107154354.jpeg
FrameNumber: 206
category: Car
Trackid: 25
width: 35.447349548339844
height: 30.643131256103516
x: 493.4872741699219
y: 248.4204864501953
TimeStamp: MFC4xxLongImageRight1469119107154354.jpeg
FrameNumber: 206
category: Car
Trackid: 17
width: 151.3157958984375
height: 111.7741928100586
x: 300.2105407714844
y: 243.9516143798828
TimeStamp: MFC4xxLongImageRight1469119108480508.jpeg
FrameNumber: 89
category: Car
Trackid: 25
width: 39.94735336303711
height: 32.90858459472656
x: 480.5789489746094
y: 242.2437744140625
TimeStamp: MFC4xxLongImageRight1469119108480508.jpeg
FrameNumber: 89
category: Car
Trackid: 17
width: 124.68421173095703
height: 92.32686614990234
x: 231.2105255126953
y: 234.9307403564453
TimeStamp: MFC4xxLongImageRight1469119098835782.jpeg
FrameNumber: 44
category: Car
Trackid: 21
width: 36.693328857421875
height: 27.233665466308594
x: 401.184814453125
y: 254.53794860839844
TimeStamp: MFC4xxLongImageRight1469119098835782.jpeg
FrameNumber: 44
category: Car
Trackid: 20
width: 59.0
height: 47.0
x: 316.78887939453125
y: 247.97528076171875
TimeStamp: MFC4xxLongImageRight1469119098835782.jpeg
FrameNumber: 44
category: Car
Trackid: 19
width: 100.47370147705078
height: 63.074798583984375
x: 211.8420867919922
y: 242.2437744140625
TimeStamp: MFC4xxLongImageRight1469119098835782.jpeg
FrameNumber: 44
category: Car
Trackid: 18
width: 144.05264282226562
height: 79.52908325195312
x: 29.05261993408203
y: 244.072021484375
TimeStamp: MFC4xxLongImageRight1469119098835782.jpeg
FrameNumber: 44
category: Car
Trackid: 17
width: 33.66328048706055
height: 24.88539695739746
x: 450.6455993652344
y: 248.92654418945312
TimeStamp: MFC4xxLongImageRight1469119102271717.jpeg
FrameNumber: 78
category: Car
Trackid: 23
width: 41.157894134521484
height: 33.822715759277344
x: 502.368408203125
y: 249.58311462402344
TimeStamp: MFC4xxLongImageRight1469119102271717.jpeg
FrameNumber: 78
category: Car
Trackid: 22
width: 144.05264282226562
height: 54.84764862060547
x: 198.52630615234375
y: 252.32550048828125
TimeStamp: MFC4xxLongImageRight1469119102271717.jpeg
FrameNumber: 78
category: Car
Trackid: 17
width: 68.5
height: 47.750003814697266
x: 428.50042724609375
y: 248.29544067382812
TimeStamp: MFC4xxLongImageRight1469119105165130.jpeg
FrameNumber: 173
category: Car
Trackid: 26
width: 82.61842346191406
height: 34.73684310913086
x: 984.7631225585938
y: 236.066650390625
TimeStamp: MFC4xxLongImageRight1469119105165130.jpeg
FrameNumber: 173
category: Car
Trackid: 25
width: 35.113338470458984
height: 27.370161056518555
x: 509.1869201660156
y: 250.07525634765625
TimeStamp: MFC4xxLongImageRight1469119105165130.jpeg
FrameNumber: 173
category: Car
Trackid: 24
width: 96.75566101074219
height: 37.56137466430664
x: 157.2819366455078
y: 259.83905029296875
TimeStamp: MFC4xxLongImageRight1469119105165130.jpeg
FrameNumber: 173
category: Car
Trackid: 17
width: 161.0
height: 111.7741928100586
x: 323.2105407714844
y: 236.85484313964844
TimeStamp: MFC4xxLongImageRight1469119098052144.jpeg
FrameNumber: 55
category: Car
Trackid: 21
width: 22.84160804748535
height: 22.17681312561035
x: 424.56890869140625
y: 247.8643035888672
TimeStamp: MFC4xxLongImageRight1469119098052144.jpeg
FrameNumber: 55
category: Car
Trackid: 15
width: 110.24634552001953
height: 65.92732238769531
x: 131.51304626464844
y: 246.6368865966797
TimeStamp: MFC4xxLongImageRight1469119098052144.jpeg
FrameNumber: 55
category: Car
Trackid: 19
width: 48.72370147705078
height: 42.098751068115234
x: 345.9078674316406
y: 238.80482482910156
TimeStamp: MFC4xxLongImageRight1469119098052144.jpeg
FrameNumber: 55
category: Car
Trackid: 18
width: 68.28971862792969
height: 45.981754302978516
x: 278.2234191894531
y: 245.5761260986328
TimeStamp: MFC4xxLongImageRight1469119098052144.jpeg
FrameNumber: 55
category: Car
Trackid: 17
width: 30.146503448486328
height: 22.120025634765625
x: 467.5987548828125
y: 250.54444885253906
TimeStamp: MFC4xxLongImageRight1469119102934793.jpeg
FrameNumber: 136
category: Car
Trackid: 23
width: 41.15788650512695
height: 33.822723388671875
x: 515.9432983398438
y: 247.9724578857422
TimeStamp: MFC4xxLongImageRight1469119102934793.jpeg
FrameNumber: 136
category: Car
Trackid: 22
width: 138.3411407470703
height: 65.02467346191406
x: 77.68282318115234
y: 254.94078063964844
TimeStamp: MFC4xxLongImageRight1469119102934793.jpeg
FrameNumber: 136
category: Car
Trackid: 17
width: 99.2631607055664
height: 65.6451644897461
x: 411.5789489746094
y: 242.1774139404297
TimeStamp: MFC4xxLongImageRight1469119102151156.jpeg
FrameNumber: 123
category: Car
Trackid: 23
width: 41.15791320800781
height: 33.82270812988281
x: 498.73681640625
y: 248.67776489257812
TimeStamp: MFC4xxLongImageRight1469119102151156.jpeg
FrameNumber: 123
category: Car
Trackid: 22
width: 133.76316833496094
height: 54.84765625
x: 219.10525512695312
y: 247.7987518310547
TimeStamp: MFC4xxLongImageRight1469119102151156.jpeg
FrameNumber: 123
category: Car
Trackid: 17
width: 61.73684310913086
height: 45.24193572998047
x: 428.52630615234375
y: 243.9516143798828
TimeStamp: MFC4xxLongImageRight1469119103597862.jpeg
FrameNumber: 147
category: Car
Trackid: 23
width: 41.15790939331055
height: 33.822723388671875
x: 510.1421813964844
y: 249.5569305419922
TimeStamp: MFC4xxLongImageRight1469119103597862.jpeg
FrameNumber: 147
category: Car
Trackid: 17
width: 112.57894897460938
height: 72.74193572998047
x: 394.631591796875
y: 242.1774139404297
TimeStamp: MFC4xxLongImageRight1469119105828207.jpeg
FrameNumber: 184
category: Car
Trackid: 26
width: 90.02408599853516
height: 35.20697021484375
x: 1025.264404296875
y: 239.11985778808594
TimeStamp: MFC4xxLongImageRight1469119105828207.jpeg
FrameNumber: 184
category: Car
Trackid: 25
width: 32.8736686706543
height: 29.34747314453125
x: 504.9278869628906
y: 251.3734130859375
TimeStamp: MFC4xxLongImageRight1469119105828207.jpeg
FrameNumber: 184
category: Car
Trackid: 24
width: 95.78922271728516
height: 39.472015380859375
x: 36.92686080932617
y: 264.1865539550781
TimeStamp: MFC4xxLongImageRight1469119105828207.jpeg
FrameNumber: 184
category: Car
Trackid: 17
width: 176.73684692382812
height: 111.7741928100586
x: 307.47369384765625
y: 236.85484313964844
TimeStamp: MFC4xxLongImageRight1469119101488082.jpeg
FrameNumber: 60
category: Car
Trackid: 22
width: 100.0983657836914
height: 47.0
x: 301.29998779296875
y: 244.92677307128906
TimeStamp: MFC4xxLongImageRight1469119101488082.jpeg
FrameNumber: 60
category: Car
Trackid: 21
width: 126.90585327148438
height: 70.01460266113281
x: 95.19588470458984
y: 249.85696411132812
TimeStamp: MFC4xxLongImageRight1469119101488082.jpeg
FrameNumber: 60
category: Car
Trackid: 17
width: 62.754608154296875
height: 43.802032470703125
x: 424.05224609375
y: 245.1049346923828
TimeStamp: MFC4xxLongImageRight1469119097509630.jpeg
FrameNumber: 46
category: Car
Trackid: 10
width: 132.3333282470703
height: 74.33332061767578
x: 100.4264907836914
y: 244.02574157714844
TimeStamp: MFC4xxLongImageRight1469119097509630.jpeg
FrameNumber: 46
category: Car
Trackid: 15
width: 64.0
height: 42.0
x: 289.96624755859375
y: 252.6454315185547
TimeStamp: MFC4xxLongImageRight1469119097509630.jpeg
FrameNumber: 46
category: Car
Trackid: 18
width: 50.03178787231445
height: 35.48387145996094
x: 349.44189453125
y: 249.27420043945312
TimeStamp: MFC4xxLongImageRight1469119097509630.jpeg
FrameNumber: 46
category: Car
Trackid: 17
width: 28.66666603088379
height: 21.33333396911621
x: 471.9822082519531
y: 248.0352020263672
TimeStamp: MFC4xxLongImageRight1469119104260935.jpeg
FrameNumber: 158
category: Car
Trackid: 23
width: 41.487403869628906
height: 33.924964904785156
x: 494.9558410644531
y: 254.34127807617188
TimeStamp: MFC4xxLongImageRight1469119104260935.jpeg
FrameNumber: 158
category: Car
Trackid: 26
width: 69.0000228881836
height: 34.73684310913086
x: 939.368408203125
y: 236.7319793701172
TimeStamp: MFC4xxLongImageRight1469119104260935.jpeg
FrameNumber: 158
category: Car
Trackid: 24
width: 53.263145446777344
height: 35.65096664428711
x: 311.10528564453125
y: 253.89231872558594
TimeStamp: MFC4xxLongImageRight1469119104260935.jpeg
FrameNumber: 158
category: Car
Trackid: 17
width: 130.73684692382812
height: 93.1451644897461
x: 364.368408203125
y: 241.2903289794922
TimeStamp: MFC4xxLongImageRight1469119107033795.jpeg
FrameNumber: 204
category: Car
Trackid: 23
width: 100.52865600585938
height: 46.78466033935547
x: 166.36904907226562
y: 264.322509765625
TimeStamp: MFC4xxLongImageRight1469119107033795.jpeg
FrameNumber: 204
category: Car
Trackid: 26
width: 85.24102783203125
height: 38.7499885559082
x: 1084.90283203125
y: 236.0831756591797
TimeStamp: MFC4xxLongImageRight1469119107033795.jpeg
FrameNumber: 204
category: Car
Trackid: 25
width: 35.28943634033203
height: 30.563640594482422
x: 493.940185546875
y: 248.63720703125
TimeStamp: MFC4xxLongImageRight1469119107033795.jpeg
FrameNumber: 204
category: Car
Trackid: 17
width: 151.3157958984375
height: 111.7741928100586
x: 300.2105407714844
y: 243.9516143798828
TimeStamp: MFC4xxLongImageRight1469119095399850.jpeg
FrameNumber: 11
category: Car
Trackid: 4
width: 113.78947448730469
height: 74.68421173095703
x: 10.894737243652344
y: 267.4736633300781
TimeStamp: MFC4xxLongImageRight1469119095399850.jpeg
FrameNumber: 11
category: Car
Trackid: 10
width: 26.63157844543457
height: 29.526315689086914
x: 381.3157958984375
y: 255.3157958984375
TimeStamp: MFC4xxLongImageRight1469119095399850.jpeg
FrameNumber: 11
category: Car
Trackid: 3
width: 28.568431854248047
height: 36.47369384765625
x: 357.3473815917969
y: 253.57894897460938
TimeStamp: MFC4xxLongImageRight1469119095399850.jpeg
FrameNumber: 11
category: Car
Trackid: 2
width: 110.0606918334961
height: 79.0
x: 130.83404541015625
y: 250.22325134277344
TimeStamp: MFC4xxLongImageRight1469119095399850.jpeg
FrameNumber: 11
category: Car
Trackid: 1
width: 62.94736862182617
height: 67.73684692382812
x: 290.52630615234375
y: 250.10525512695312
TimeStamp: MFC4xxLongImageRight1469119100945567.jpeg
FrameNumber: 56
category: Car
Trackid: 22
width: 66.84687805175781
height: 37.89362335205078
x: 354.416259765625
y: 246.18519592285156
TimeStamp: MFC4xxLongImageRight1469119100945567.jpeg
FrameNumber: 56
category: Car
Trackid: 21
width: 85.0
height: 53.0
x: 238.42352294921875
y: 250.4225311279297
TimeStamp: MFC4xxLongImageRight1469119100945567.jpeg
FrameNumber: 56
category: Car
Trackid: 17
width: 54.26382064819336
height: 37.40610122680664
x: 426.70843505859375
y: 247.59658813476562
TimeStamp: MFC4xxLongImageRight1469119100161930.jpeg
FrameNumber: 56
category: Car
Trackid: 21
width: 46.88090896606445
height: 34.29314422607422
x: 336.4839172363281
y: 248.5045928955078
TimeStamp: MFC4xxLongImageRight1469119100161930.jpeg
FrameNumber: 56
category: Car
Trackid: 20
width: 59.31578063964844
height: 86.84210968017578
x: 9.637129551265389e-06
y: 244.072021484375
TimeStamp: MFC4xxLongImageRight1469119100161930.jpeg
FrameNumber: 56
category: Car
Trackid: 17
width: 40.6491584777832
height: 30.183517456054688
x: 439.4967956542969
y: 246.72332763671875
TimeStamp: MFC4xxLongImageRight1469119095279289.jpeg
FrameNumber: 9
category: Car
Trackid: 4
width: 113.78947448730469
height: 74.68421173095703
x: 50.842105865478516
y: 260.52630615234375
TimeStamp: MFC4xxLongImageRight1469119095279289.jpeg
FrameNumber: 9
category: Car
Trackid: 3
width: 21.789474487304688
height: 36.47369384765625
x: 370.4210510253906
y: 253.57894897460938
TimeStamp: MFC4xxLongImageRight1469119095279289.jpeg
FrameNumber: 9
category: Car
Trackid: 2
width: 95.631591796875
height: 79.89473724365234
x: 168.26315307617188
y: 246.63157653808594
TimeStamp: MFC4xxLongImageRight1469119095279289.jpeg
FrameNumber: 9
category: Car
Trackid: 1
width: 62.94736862182617
height: 67.73684692382812
x: 303.84210205078125
y: 241.42105102539062
TimeStamp: MFC4xxLongImageRight1469119100825007.jpeg
FrameNumber: 66
category: Car
Trackid: 22
width: 67.78948211669922
height: 33.11723327636719
x: 365.5789489746094
y: 249.8765411376953
TimeStamp: MFC4xxLongImageRight1469119100825007.jpeg
FrameNumber: 66
category: Car
Trackid: 21
width: 74.4677734375
height: 49.39211654663086
x: 264.8631591796875
y: 249.5500030517578
TimeStamp: MFC4xxLongImageRight1469119100825007.jpeg
FrameNumber: 66
category: Car
Trackid: 17
width: 51.07977294921875
height: 35.00762176513672
x: 427.70452880859375
y: 248.53094482421875
TimeStamp: MFC4xxLongImageRight1469119104381496.jpeg
FrameNumber: 160
category: Car
Trackid: 23
width: 42.14635467529297
height: 34.12944793701172
x: 490.709716796875
y: 253.888671875
TimeStamp: MFC4xxLongImageRight1469119104381496.jpeg
FrameNumber: 160
category: Car
Trackid: 26
width: 70.81578826904297
height: 34.73683166503906
x: 945.4210205078125
y: 236.6432647705078
TimeStamp: MFC4xxLongImageRight1469119104381496.jpeg
FrameNumber: 160
category: Car
Trackid: 24
width: 70.21051788330078
height: 35.65095901489258

In [11]:
len(TimeStamp),len(FrameNumber),len(category),len(Trackid),len(width),len(height),len(x),len(y)

(850, 850, 850, 850, 850, 850, 850, 850)

In [12]:
import json

with open('1.TimeStamp.json','w') as file1:
    json.dump(TimeStamp, file1)
    
with open('2.FrameNumber.json','w') as file2:
    json.dump(FrameNumber, file2)

with open('3.category.json','w') as file3:
    json.dump(category, file3)

with open('4.Trackid.json','w') as file6:
    json.dump(Trackid, file6)
    
with open('5.width.json','w') as file4:
    json.dump(width, file4)
    
with open('6.height.json','w') as file5:
    json.dump(height, file5)
    
with open('7.x.json','w') as file7:
    json.dump(x, file7)
    
with open('8.y.json','w') as file8:
    json.dump(y, file8)

In [13]:
import pandas as pd

with open('1.TimeStamp.json', encoding='utf-8') as inputfile:
    df = pd.read_json(inputfile)

df.to_csv('1.TimeStamp.csv', encoding='utf-8', index=False)

with open('2.FrameNumber.json', encoding='utf-8') as inputfile:
    df = pd.read_json(inputfile)

df.to_csv('2.FrameNumber.csv', encoding='utf-8', index=False)

with open('3.category.json', encoding='utf-8') as inputfile:
    df = pd.read_json(inputfile)

df.to_csv('3.category.csv', encoding='utf-8', index=False)

with open('4.Trackid.json', encoding='utf-8') as inputfile:
    df = pd.read_json(inputfile)

df.to_csv('4.Trackid.csv', encoding='utf-8', index=False)

with open('5.width.json', encoding='utf-8') as inputfile:
    df = pd.read_json(inputfile)

df.to_csv('5.width.csv', encoding='utf-8', index=False)

with open('6.height.json', encoding='utf-8') as inputfile:
    df = pd.read_json(inputfile)

df.to_csv('6.height.csv', encoding='utf-8', index=False)

with open('7.x.json', encoding='utf-8') as inputfile:
    df = pd.read_json(inputfile)

df.to_csv('7.x.csv', encoding='utf-8', index=False)

with open('8.y.json', encoding='utf-8') as inputfile:
    df = pd.read_json(inputfile)

df.to_csv('8.y.csv', encoding='utf-8', index=False)

In [14]:
import glob, os, json

json_dir = 'C:\\Users\\uif68352\\Active_Learning\\Labelled_230_car_images\\Jsons_and_csv'

json_pattern = os.path.join(json_dir, '*.json')
file_list = glob.glob(json_pattern)
print(file_list)

['C:\\Users\\uif68352\\Active_Learning\\Labelled_230_car_images\\Jsons_and_csv\\1.TimeStamp.json', 'C:\\Users\\uif68352\\Active_Learning\\Labelled_230_car_images\\Jsons_and_csv\\2.FrameNumber.json', 'C:\\Users\\uif68352\\Active_Learning\\Labelled_230_car_images\\Jsons_and_csv\\3.category.json', 'C:\\Users\\uif68352\\Active_Learning\\Labelled_230_car_images\\Jsons_and_csv\\4.Trackid.json', 'C:\\Users\\uif68352\\Active_Learning\\Labelled_230_car_images\\Jsons_and_csv\\5.width.json', 'C:\\Users\\uif68352\\Active_Learning\\Labelled_230_car_images\\Jsons_and_csv\\6.height.json', 'C:\\Users\\uif68352\\Active_Learning\\Labelled_230_car_images\\Jsons_and_csv\\7.x.json', 'C:\\Users\\uif68352\\Active_Learning\\Labelled_230_car_images\\Jsons_and_csv\\8.y.json']

In [15]:
import pandas as pd
dfs = []
for file in file_list:
    df_temp = pd.read_json(file,  lines=True)
    df_temp['source'] = file.rsplit("/", 1)[-1]
    dfs.append(df_temp)
df = pd.concat(dfs)
df = df.T

In [16]:
df.columns=['TimeStamp','FrameNumber','category','Trackid','width','height','x','y']
df = df.iloc[:-1]
display(df)

,TimeStamp,FrameNumber,category,Trackid,width,height,x,y
0,MFC4xxLongImageRight1469119107817429.jpeg,80,Car,23,112.24987,48.340721,20.414988,267.947174
1,MFC4xxLongImageRight1469119107817429.jpeg,80,Car,25,37.105244,31.477768,488.731567,246.144852
2,MFC4xxLongImageRight1469119107817429.jpeg,80,Car,17,130.82135,100.538826,271.070435,239.280121
3,MFC4xxLongImageRight1469119105707648.jpeg,182,Car,26,92.235817,34.956238,1016.99408,238.688232
4,MFC4xxLongImageRight1469119105707648.jpeg,182,Car,25,32.810505,29.315674,505.688782,251.377289
...,...,...,...,...,...,...,...,...
845,MFC4xxLongImageRight1469119096183481.jpeg,24,Car,1,136.27655,88,94.933975,246.734116
846,MFC4xxLongImageRight1469119096183481.jpeg,24,Car,17,27.875004,21.74342,450.164093,259.305023
847,MFC4xxLongImageRight1469119107937991.jpeg,82,Car,23,108.040459,49.022163,1.10724,268.334961
848,MFC4xxLongImageRight1469119107937991.jpeg,82,Car,25,37.736824,31.795723,486.919891,245.277954
849,MFC4xxLongImageRight1469119107937991.jpeg,82,Car,17,129.457535,98.713951,262.212677,238.313599

In [17]:
df_sorted = df.sort_values('FrameNumber')
df_sorted

,TimeStamp,FrameNumber,category,Trackid,width,height,x,y
32,MFC4xxLongImageRight1469119094736776.jpeg,0,Car,3,21.789474,26.052631,409.157898,257.052643
33,MFC4xxLongImageRight1469119094736776.jpeg,0,Car,2,60.526318,57.315788,279.631592,248.368423
35,MFC4xxLongImageRight1469119094736776.jpeg,0,Car,0,104.105263,52.105263,169.473679,264
34,MFC4xxLongImageRight1469119094736776.jpeg,0,Car,1,41.157894,50.36842,347.421051,248.368423
368,MFC4xxLongImageRight1469119094797056.jpeg,1,Car,2,81.105278,60.789471,256.631592,243.157898
...,...,...,...,...,...,...,...,...
331,MFC4xxLongImageRight1469119108118826.jpeg,222,Car,23,71.421066,45.82011,1.210513,267.325043
332,MFC4xxLongImageRight1469119108118826.jpeg,222,Car,25,38.210495,32.034187,485.561096,244.627777
333,MFC4xxLongImageRight1469119108118826.jpeg,222,Car,17,129.457535,98.713951,262.212677,238.313599
494,MFC4xxLongImageRight1469119108540783.jpeg,229,Car,25,39.947353,32.908585,480.578949,242.243774
495,MFC4xxLongImageRight1469119108540783.jpeg,229,Car,17,129.457535,98.713951,227.107407,235.652313

In [18]:
df_sorted.to_csv('labels_for_230_car_images.csv', encoding='utf-8', index=True)